apiVersion: v1
items:
- apiVersion: v1
  imagePullSecrets:
  - name: builder-dockercfg-6fftq
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2020-06-22T13:36:58Z"
    name: builder
    namespace: lab-operator
    resourceVersion: "241774"
    selfLink: /api/v1/namespaces/lab-operator/serviceaccounts/builder
    uid: 723f640d-b48d-11ea-8277-0a3db79e8570
  secrets:
  - name: builder-token-wrcxc
  - name: builder-dockercfg-6fftq
- apiVersion: v1
  imagePullSecrets:
  - name: default-dockercfg-dnq2n
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2020-06-22T13:36:58Z"
    name: default
    namespace: lab-operator
    resourceVersion: "241776"
    selfLink: /api/v1/namespaces/lab-operator/serviceaccounts/default
    uid: 723eec27-b48d-11ea-8277-0a3db79e8570
  secrets:
  - name: default-token-gvbfs
  - name: default-dockercfg-dnq2n
- apiVersion: v1
  imagePullSecrets:
  - name: deployer-dockercfg-8fwch
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2020-06-22T13:36:58Z"
    name: deployer
    namespace: lab-operator
    resourceVersion: "241772"
    selfLink: /api/v1/namespaces/lab-operator/serviceaccounts/deployer
    uid: 7240db08-b48d-11ea-8277-0a3db79e8570
  secrets:
  - name: deployer-token-lb592
  - name: deployer-dockercfg-8fwch
- apiVersion: v1
  imagePullSecrets:
  - name: lab-build-an-operator-spawner-dockercfg-lcr2c
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"lab-build-an-operator","class":"spawner","spawner":"learning-portal"},"name":"lab-build-an-operator-spawner","namespace":"lab-operator"}}
    creationTimestamp: "2020-06-22T13:39:34Z"
    labels:
      app: lab-build-an-operator
      class: spawner
      spawner: learning-portal
    name: lab-build-an-operator-spawner
    namespace: lab-operator
    resourceVersion: "242472"
    selfLink: /api/v1/namespaces/lab-operator/serviceaccounts/lab-build-an-operator-spawner
    uid: cf45d2d9-b48d-11ea-9db7-0a64f989d73e
  secrets:
  - name: lab-build-an-operator-spawner-dockercfg-lcr2c
  - name: lab-build-an-operator-spawner-token-pxh5f
- apiVersion: v1
  imagePullSecrets:
  - name: lab-build-an-operator-user1-dockercfg-c5nc8
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2020-06-26T12:05:45Z"
    labels:
      app: lab-build-an-operator
      class: session
      spawner: learning-portal
      user: user1
    name: lab-build-an-operator-user1
    namespace: lab-operator
    resourceVersion: "2614453"
    selfLink: /api/v1/namespaces/lab-operator/serviceaccounts/lab-build-an-operator-user1
    uid: 5d44e9f1-b7a5-11ea-bd2a-0a3db79e8570
  secrets:
  - name: lab-build-an-operator-user1-token-wz8f5
  - name: lab-build-an-operator-user1-dockercfg-c5nc8
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
